export const projects = [
  {
    id: 1,
    image: "/ProjectsImg/project-img1.png",
    title: "Coastal Luxury",
    address: "Cabo San Lucas, Mexico",
    rooms: "7 bed, 7 bath, 2 half-bath",
    type: "Vacation Home, New Construction",
    size: "21,928 sq.ft.",
  },
  {
    id: 2,
    image: "/ProjectsImg/project-img2.png",
    title: "Murano at Portofino",
    address: "Miami, FL",
    size: "3,905 sq.ft.",
    type: "Condo, Furnishing",
    rooms: "3 Beds, 3.5 Baths",
  },
  {
    id: 3,
    image: "/ProjectsImg/project-img3.png",
    title: "Palm Beach Ocean View",
    address: "Palm Beach, FL",
    size: "3 073 sq.ft.",
    type: "Condo, Remodel",
    rooms: "3 Beds, 3 Baths",
  },
  {
    id: 4,
    image: "/ProjectsImg/project-img4.png",
    title: "Intracoastal Remodel",
    address: "Delray Beach, FL",
    rooms: "4 Beds, 6.5 Baths",
    type: "Single Family Home, Remodel",
    size: "7 962 sq.ft.",
  },
  {
    id: 5,
    image: "/ProjectsImg/project-img5.png",
    title: "Cake House",
    address: "Boca Raton, FL",
    rooms: "3 Beds, 3.5 Baths",
    size: "2 847 sq.ft.",
    type: "New Construction Condo",
  },
  {
    id: 6,
    image: "/ProjectsImg/project-img6.png",
    title: "Miami Serenity Villa",
    address: "Miami, FL",
    rooms: "7 bed, 7 bath, 2 half-bath",
    type: "Condo Remodel",
    size: "21,928 sq.ft.",
  },
  {
    id: 7,
    image: "/ProjectsImg/project-img7.png",
    title: "Serenity Residence",
    address: "Boca Raton, FL",
    rooms: "3 Bed / 3 Bath",
    size: "2676 Sq. Ft.",
    type: "New Construction Condo",
  },
  {
    id: 8,
    image: "/ProjectsImg/project-img8.png",
    title: "Boca Beach Residence",
    address: "Boca Raton, FL",
    rooms: "3 bed/2,5 bath",
    size: "3,600 Sq.Ft.",
    type: "New Construction Condo",
  },
  {
    id: 9,
    image: "/ProjectsImg/project-img9.png",
    title: "Dream Nursery",
    address: "Boca Raton, FL",
    rooms: "",
    type: "Condo Remodel",
    size: "",
  },
  {
    id: 10,
    image: "/ProjectsImg/project-img10.png",
    title: "Armani Casa",
    address: "Sunny Isles, FL",
    rooms: "3 Beds, 3.5 Baths With Study",
    size: "5280 sq.ft.",
    type: "Condo, Remodel",
  },
];
